name: Development CI

on:
  pull_request:
    branches: [ develop ]
    types: [opened, synchronize, reopened]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run HTMLHint
      run: npx htmlhint "**/*.html"
    
    - name: Run Stylelint
      run: npx stylelint "**/*.css"
    
    - name: Verify Links
      run: |
        npm install -g markdown-link-check
        find . -name "*.md" | xargs -I {} markdown-link-check -c ./linkcheck-config.json {}
    
    - name: Build verification
      run: |
        echo "Verifying build process..."
        # Add any build verification steps here