name: Development CI - PR Validation

on:
  pull_request:
    branches: [ develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
  
    - name: Install dependencies
      run: npm install
    
    - name: Run HTMLHint
      run: npx htmlhint "**/*.html" --config .htmlhintrc
    
    - name: Run Stylelint
      run: npx stylelint "**/*.css" --config .stylelintrc
    
    - name: Verify required files exist
      run: |
        if [ ! -f "index.html" ]; then
          echo "Error: Missing index.html file"
          exit 1
        fi
        if [ ! -f "about.html" ]; then
          echo "Error: Missing about.html file"
          exit