name: Production CD

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production-env
    needs: production-checks
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm ci --production
    
    - name: Build for production
      run: |
        echo "Building optimized production version..."
        # Add production build commands
    
    - name: Deploy to Production
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: production
        cname: travelease-pk.com  # Replace with your domain
    
    - name: Run smoke tests
      run: |
        echo "Running smoke tests on production..."
        # Add smoke test commands
    
    - name: Notify deployment
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "Production deployment completed! Visit https://travelease-pk.com"
        SLACK_COLOR: ${{ job.status }}  # Will be 'good' or 'danger'
    
    - name: Create release tag
      if: success()
      run: |
        version=$(node -p "require('./package.json').version")
        git tag -a v$version -m "Release v$version"
        git push origin v$version