name: Production CI - Final Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run HTMLHint
      run: npx htmlhint "**/*.html" --config .htmlhintrc
    
    - name: Run Stylelint
      run: npx stylelint "**/*.css" --config .stylelintrc