name: Staging CI - Release Validation

on:
  pull_request:
    branches: [ release ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
  
    - name: Run HTMLHint
      run: npx htmlhint "**/*.html"
    
    - name: Run Stylelint
      run: npx stylelint "**/*.css" 